# Generated by Django 3.1.3 on 2021-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20211111_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
