# Generated by Django 3.1.3 on 2021-11-21 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0009_auto_20211119_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reporter',
            field=models.ManyToManyField(related_name='reporter_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
