# Generated by Django 3.1.3 on 2021-11-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_comment_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
